services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=debug"
      - "--log-format=text"
      - "--watch"
      - "--config-file=/config/opa.yaml"
      - "/policies"
    volumes:
      - ./policies:/policies:ro
      - ./config:/config:ro
    working_dir: /policies
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.http.routers.opa.rule=Host(`opa.localhost`)"
      - "traefik.http.routers.opa.tls=true"
      - "traefik.http.routers.service=opa"
      - "traefik.http.services.opa.loadbalancer.server.port=8181"
    restart: unless-stopped

networks:
  traefik:
    external: true
