# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb-password
    volumes:
      - mongodb-etc:/etc/mongo
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb-password
      ME_CONFIG_MONGODB_URL: mongodb://root:mongodb-password@mongo:27017/
    ports:
      - 8027:8081
    networks:
      - mongo

networks:
  mongo:

volumes:
  mongodb-etc:
  mongodb-data:

