# ------------------------------------------------------------
# docker-compose.yml for an OpenSSH Server
# ------------------------------------------------------------

version: "3.1"

services:

  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      #- PUBLIC_KEY=yourpublickey #optional
      #- PUBLIC_KEY_FILE=/path/to/file #optional
      #- PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      #- PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - PASSWORD_ACCESS=true
      - USER_NAME=alice
      - USER_PASSWORD=s3cret
    volumes:
      - ./config:/config
    ports:
      - 2222:2222
